version: 2.1

defaults: &defaults
  working_directory: ~/repo

executors:
  node14:
    docker:
      - image: circleci/node:14
  node12:
    docker:
      - image: circleci/node:12.6

workflows:
  version: 2
  build:
    jobs:
      - build_and_test:
          name: build_node14
          executor: node14
      - build_and_test:
          name: build_node12
          executor: node12
      - deploy_prerelease:
          requires:
            - build_node14
            - build_node12
          filters:
            branches:
              only: master

jobs:
  build_and_test:
    <<: *defaults
    parameters:
      executor:
        default: node12
        type: string
    executor: "<< parameters.executor >>"

    steps:
      - prepare
        
      # run tests!
      - run: yarn ci
  
  deploy_prerelease:
    <<: *defaults
    executor: node12
    steps:
      - prepare

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: Publish package
          command: yarn publish:prerelease

commands:
  prepare:
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "yarn.lock" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}  